### ISSUE TITLE
PA Review: User Auth

### ISSUE THREAD

**Issue by iProgYou** [iProgYou/Tubetube#2]
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components and Containers
- [ ] Styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seed

**Comment by samwalker191** [comment]
- [ ] Login button should be styled on header component
- [ ] When user is signed in, its hard to see their info. That'll be fixed when you have the icon thing as well as a dropdown for that

The search bar needs a little work on styling, but that is not required for this MVP.

**Comment by iProgYou** [comment]
Awesome Ya I will be working on the Navbar portion today, but it seems like the login/signup/demo are good to go?

**Comment by samwalker191** [comment]
Yep! What you have looks good, once the navbar is finished we can close this issue. Nice job.

**Comment by iProgYou** [comment]
It took me all day but it is finally finished lol

**Comment by samwalker191** [comment]
Few more things!
- [ ] The spacing to the left of the icon in the sign in button should be the same size as the spacing to the right of the sign in text
- [ ] the drop down menu items should have a hover effect that changes their background color
- [ ] the search bar shouldn't jiggle when the user signs in and out

**Comment by iProgYou** [comment]
RE the search bar, it is positioned differently for a logged in vs logged out user on Youtube, similar to how mine is(though it is not as obvious because you cant log out as easily). Should I prioritize getting rid of the jiggle over site accuracy in this case?

**Comment by samwalker191** [comment]
Ahh I see. I didn't realize theirs moved. I never noticed that. I'd say its fine then as is.

**Comment by iProgYou** [comment]
I fixed it regardless haha it def looks cleaner with it not moving so I'll leave it, unless it looks weird to you
